//
// Created by mathieu on 07/07/2021.
//

#ifndef DDGI_DCCPP_DCCPP_DLG_DEFINITIONS_H
#define DDGI_DCCPP_DCCPP_DLG_DEFINITIONS_H

//
// IDs attached to DCCPP parameter dialog
//
#define DCCPP_PARAM_DLG 60500

// Radios
#define DCCPP_PARAM_DLG_USB_RADIO 60510
#define DCCPP_PARAM_DLG_WIFI_RADIO 60511

// Inputs
#define DCCPP_PARAM_DLG_COM_LIST 60520
#define DCCPP_PARAM_DLG_IP_EDITTEXT 60521
#define DCCPP_PARAM_DLG_S88_EDITTEXT 60522

// Buttons
#define DCCPP_PARAM_DLG_CONNECTION_BUTTON 60530
#define DCCPP_PARAM_DLG_CANCEL_BUTTON 60531
#define DCCPP_PARAM_DLG_SCAN_BUTTON 60532

// Labels
#define DCCPP_PARAM_DLG_COM_LABEL 60540
#define DCCPP_PARAM_DLG_IP_LABEL 60541

//
// IDs attached to DCCPP progress dialog
//
#define DCCPP_PROGRESS_DLG 60600
#define DCCPP_PROGRESS_DLG_PROG 60601

#endif // DDGI_DCCPP_DCCPP_DLG_DEFINITIONS_H
